# Generated by Django 4.0.3 on 2022-05-10 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slms_web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_model',
            name='approved_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam_model',
            name='approved_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam_model',
            name='published_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question_paper_model',
            name='approved_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question_paper_model',
            name='published_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='study_material',
            name='approved_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='director_user',
            name='active_status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Inactive'), ('3', 'On-hold')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='exam_paper_detail',
            name='exam_end_date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 14, 41, 32, 521395)),
        ),
        migrations.AlterField(
            model_name='exam_paper_detail',
            name='exam_start_date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 14, 41, 32, 521395)),
        ),
        migrations.AlterField(
            model_name='parent_user',
            name='active_status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Inactive'), ('3', 'On-hold')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='principal_user',
            name='active_status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Inactive'), ('3', 'On-hold')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='schooladmin_user',
            name='active_status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Inactive'), ('3', 'On-hold')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='student_user',
            name='active_status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Inactive'), ('3', 'On-hold')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='teacher_user',
            name='active_status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Inactive'), ('3', 'On-hold')], default='2', max_length=1),
        ),
    ]
