# Generated by Django 4.0.3 on 2022-05-11 05:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slms_web_app', '0004_alter_assignment_model_approved_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_paper_detail',
            name='exam_end_date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 11, 11, 12, 12, 989022)),
        ),
        migrations.AlterField(
            model_name='exam_paper_detail',
            name='exam_start_date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 11, 11, 12, 12, 989022)),
        ),
        migrations.CreateModel(
            name='time_table_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_table_ID', models.CharField(max_length=50, unique=True)),
                ('time_table_session', models.CharField(default='', max_length=50)),
                ('time_table_effective_from', models.CharField(choices=[('1', 'January'), ('2', 'Feburary'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default='0', max_length=2)),
                ('monday_slot', models.TextField(default='[]')),
                ('tuesday_slot', models.TextField(default='[]')),
                ('wednesday_slot', models.TextField(default='[]')),
                ('thursday_slot', models.TextField(default='[]')),
                ('friday_slot', models.TextField(default='[]')),
                ('saturday_slot', models.TextField(default='[]')),
                ('time_table_active_status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive'), ('3', 'Pending')], default='2', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='superAdmin', max_length=200)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('branch_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slms_web_app.branch', verbose_name='branch_fk')),
                ('class_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slms_web_app.class_master', verbose_name='class_fk')),
                ('section_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slms_web_app.section_master', verbose_name='section_fk')),
                ('year_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slms_web_app.year_master', verbose_name='year_fk')),
            ],
            options={
                'unique_together': {('time_table_session', 'time_table_effective_from', 'year_fk', 'branch_fk', 'class_fk', 'section_fk')},
            },
        ),
    ]
