# Generated by Django 4.0.3 on 2022-05-12 08:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slms_web_app', '0005_alter_exam_paper_detail_exam_end_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_paper_detail',
            name='exam_end_date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 12, 13, 30, 23, 201714)),
        ),
        migrations.AlterField(
            model_name='exam_paper_detail',
            name='exam_start_date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 12, 13, 30, 23, 201714)),
        ),
        migrations.CreateModel(
            name='attendance_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_ID', models.CharField(max_length=50, unique=True)),
                ('attendance_session', models.CharField(default='', max_length=50)),
                ('attendance_status', models.CharField(choices=[('1', 'Present'), ('2', 'Absent'), ('3', 'Pending')], default='3', max_length=1)),
                ('attendance_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='superAdmin', max_length=200)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('branch_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slms_web_app.branch', verbose_name='branch_fk')),
                ('class_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slms_web_app.class_master', verbose_name='class_fk')),
                ('section_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slms_web_app.section_master', verbose_name='section_fk')),
                ('student_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slms_web_app.student_profile', verbose_name='student_fk')),
            ],
            options={
                'unique_together': {('attendance_ID', 'attendance_session', 'student_fk', 'branch_fk', 'class_fk', 'section_fk', 'attendance_date')},
            },
        ),
    ]
