# Generated by Django 4.0.3 on 2022-05-16 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slms_web_app', '0006_alter_exam_paper_detail_exam_end_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_paper_detail',
            name='exam_end_date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 13, 37, 45, 490550)),
        ),
        migrations.AlterField(
            model_name='exam_paper_detail',
            name='exam_start_date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 13, 37, 45, 490550)),
        ),
    ]
